# Generated by Django 4.0.4 on 2023-07-31 14:06

import airport_service.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airport_service', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='airplane',
            name='crew',
        ),
        migrations.AddField(
            model_name='flight',
            name='crew',
            field=models.ManyToManyField(to='airport_service.crew'),
        ),
        migrations.AddField(
            model_name='flight',
            name='image',
            field=models.ImageField(null=True, upload_to=airport_service.models.flight_image_file_path),
        ),
    ]
